force-app/main/default/objects/Contact/fields/ROI_City__c.field-meta.xml
<CustomField>
    <fullName>ROI_City__c</fullName>
    <label>ROI City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Location_Updated__e/Contact_Location_Updated__e.object-meta.xml
<CustomObject>
    <description>track Contact geolocation changes</description>
    <label>Contact Location Updated</label>
    <pluralLabel>Contact Location Updated</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact_Location_Updated__e/fields/ROI_City__c.field-meta.xml
<CustomField>
    <fullName>ROI_City__c</fullName>
    <label>ROI City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Location_Updated__e/fields/ROI_Latitude__c.field-meta.xml
<CustomField>
    <fullName>ROI_Latitude__c</fullName>
    <label>ROI Latitude</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact_Location_Updated__e/fields/ROI_Longitude__c.field-meta.xml
<CustomField>
    <fullName>ROI_Longitude__c</fullName>
    <label>ROI Longitude</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PlatformEvent.cls
public class PlatformEvent {

    public static void publishContactLocationUpdated(List<Contact> contacts) {
        List<Contact_Location_Updated__e> notifications = new List<Contact_Location_Updated__e>();

        for(Contact con : contacts) {
            notifications.add(
                new Contact_Location_Updated__e(
                    Account_Id__c = (String)con.AccountId,
                    Contact_Id__c = (String)con.Id,
                    ROI_City__c = con.ROI_City__c,
                    ROI_Latitude__c = con.ROI_Location__Latitude__s,
                    ROI_Longitude__c = con.ROI_Location__Longitude__s
                ));
        }

        List<Database.SaveResult> results = EventBus.publish(notifications);

        for (Database.SaveResult result : results) {
            if (!result.isSuccess()) {
                for (Database.Error error : result.getErrors()) {
                    System.debug('Error returned: ' +
                        error.getStatusCode() +' - '+
                        error.getMessage());
                }
            } else {
                System.debug('Successfully published event.');
            }
        }
    }

}